ftr(ctl): add deploy command

diff --git a/ctl/ctl b/ctl/ctl
--- a/ctl/ctl
+++ b/ctl/ctl
@@ -27,7 +27,8 @@ ctl_usage() {
 	# :command.usage_commands
 	printf "%s\n" "Commands:"
 	printf "  %s   Regenerate ctl script.\n" "bashly   "
-	printf "  %s   Write the bootstrap iso image to a device.\n" "bootstrap"
+	printf "  %s   Write the Outpost Bootstrap iso image to a device.\n" "bootstrap"
+	printf "  %s   Push configuration to Outpost.\n" "deploy   "
 	echo
 
 	# :command.long_usage
@@ -68,7 +69,7 @@ ctl_bashly_usage() {
 
 # :command.usage
 ctl_bootstrap_usage() {
-	printf "ctl bootstrap - Write the bootstrap iso image to a device.\n\n"
+	printf "ctl bootstrap - Write the Outpost Bootstrap iso image to a device.\n\n"
 
 	printf "%s\n" "Usage:"
 	printf "  ctl bootstrap DEVICE [OPTIONS]\n"
@@ -100,7 +101,34 @@ ctl_bootstrap_usage() {
 
 		# :command.usage_examples
 		printf "%s\n" "Examples:"
-		printf "  ctl bootstrap /dev/sda1\n"
+		printf "  ctl bootstrap /dev/sdb\n"
+		printf "  ctl bootstrap /dev/sdb --yes\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+ctl_deploy_usage() {
+	printf "ctl deploy - Push configuration to Outpost.\n\n"
+
+	printf "%s\n" "Usage:"
+	printf "  ctl deploy\n"
+	printf "  ctl deploy --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n "$long_usage" ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+		# :command.usage_examples
+		printf "%s\n" "Examples:"
+		printf "  ctl deploy\n"
 		echo
 
 	fi
@@ -224,6 +252,16 @@ ctl_bootstrap_command() {
 
 }
 
+# :command.function
+ctl_deploy_command() {
+
+	# src/deploy_command.sh
+	# shellcheck shell=bash
+
+	deploy
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
 	# :command.fixed_flags_filter
@@ -265,6 +303,13 @@ parse_requirements() {
 			action="bootstrap"
 			shift
 			ctl_bootstrap_parse_requirements "$@"
+			shift $#
+			;;
+
+		deploy)
+			action="deploy"
+			shift
+			ctl_deploy_parse_requirements "$@"
 			shift $#
 			;;
 
@@ -414,6 +459,51 @@ ctl_bootstrap_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+ctl_deploy_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+			--help | -h)
+				long_usage=yes
+				ctl_deploy_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="deploy"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
 # :command.initialize
 initialize() {
 	declare -g version="1.0.0"
@@ -436,6 +526,7 @@ run() {
 	case "$action" in
 		"bashly") ctl_bashly_command ;;
 		"bootstrap") ctl_bootstrap_command ;;
+		"deploy") ctl_deploy_command ;;
 	esac
 }
 
